spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_HOST_GITHUB:https://github.com/sfidencio/mvp-ecommerce-java}
          search-paths: profiles
        bootstrap: true
server:
  port: ${CONFIG_SERVER_PORT:8080}

logging:
  level:
    root: ${CONFIG_SERVER_LOG_LEVEL:info}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_TYPE_PROTOCOL:http}://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/