spring:
  application:
    name: product-service
  cloud:
    config:
      name: product-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
logging:
  level:
    root: trace
