spring:
  application:
    name: product-service
  data:
    mongodb:
      host: ${MONGO_SERVICE_HOST:localhost}
      port: ${MONGO_SERVICE_PORT:27017}
      database: ${MONGO_SERVICE_DATABASE:productdb}
      username: ${MONGO_USER:root}
      password: ${MONGO_PASSWORD:root}
      authentication-database: ${MONGO_AUTHENTICATION_DATABASE:admin}
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: true

##  cloud:
#    config:
#      uri: http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8081}
#      name: ${PRODUCT_SERVICE_HOST:product-service}
server:
  port: ${PRODUCT_SERVICE_PORT:8082}

logging:
  level:
    root: ${PRODUCT_SERVER_LOG_LEVEL:info}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_TYPE_PROTOCOL:http}://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html