spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://${MONGO_SERVICE_HOST:localhost}:${MONGO_SERVICE_PORT:27017}/${MONGO_SERVICE_DATABASE:productdb}
      username: ${MONGO_USER:admin}
      password: ${MONGO_PASSWORD:admin}
#  cloud:
#    config:
#      uri: http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8081}
#      name: ${PRODUCT_SERVICE_HOST:product-service}
server:
  port: ${PRODUCT_SERVICE_PORT:8082}

logging:
  level:
    root: ${PRODUCT_SERVER_LOG_LEVEL:info}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_TYPE_PROTOCOL:http}://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/