spring:
  application:
    name: discovery-service
server:
  port: ${EUREKA_SERVER_PORT:8761}

logging:
  level:
    root: ${EUREKA_SERVER_LOG_LEVEL:info}


eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_TYPE_PROTOCOL:http}://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/
