name: CI/CD pipeline for Multi-Module Project

on:
  push:
    branches:
      - develop


jobs:
    validate-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Validate commit message
              run: |
                  git log -1 --pretty=%B | grep -qE '^(feat|fix|docs|style|refactor|perf|test|chore|ci): .+'
                  if [ $? -ne 0 ]; then
                    echo "Invalid commit message format. Please use the conventional commit format."
                    exit 1
                fi