name: CI/CD pipeline for Multi-Module Project in develop

on:
  push:
    branches:
      - develop

jobs:
  validate-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate commit message
        run: |
          git log -1 --pretty=%B | grep -qE '^(feat|fix|docs|style|refactor|perf|test|chore|ci)\([a-z0-9_-]+\): .+'
          if [ $? -ne 0 ]; then
            echo "**********************************"
            echo "Formato de mensagem de commit inválido."
            echo "Use o formato: tipo(escopo): mensagem"
            echo "Exemplos:"
            echo "  feat(user): add login feature"
            echo "  fix(api): fix status code"
            echo "  docs(readme): update docs"
            echo "**********************************"
            echo "Para corrigir a mensagem de commit, use o seguinte comando:"
            echo "git commit --amend -m 'feat(user): add login feature'"
            echo "Ou via rebase interativo:"
            echo "git rebase -i HEAD~n"
            echo "Onde 'n' é o número de commits a serem corrigidos."
            echo "Em seguida altera a mensagem e mude 'pick' para 'reword'."
            echo "Depois faça o push forçado:"
            exit 1
          fi